# Generated by Django 5.2.8 on 2025-11-15 08:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name, e.g. Dev India, Prod EU', max_length=100)),
                ('env_type', models.CharField(choices=[('dev', 'Development'), ('staging', 'Staging'), ('uat', 'UAT'), ('prod', 'Production'), ('other', 'Other')], default='dev', max_length=20)),
                ('base_url', models.URLField(blank=True, help_text='Main site URL for this environment, if any.', null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['project', 'env_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('code', models.SlugField(help_text='Short code, e.g. kamsoft, kilowott', unique=True)),
                ('contact_person', models.CharField(blank=True, max_length=200)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('blocked', 'Blocked'), ('done', 'Done / Completed'), ('cancelled', 'Cancelled')], default='open', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('activity_type', models.CharField(blank=True, help_text='e.g. SSL renew, DNS change, backup, migration', max_length=100)),
                ('activity_date', models.DateField(help_text='Planned or actual working date for this issue.')),
                ('due_date', models.DateField(blank=True, help_text='Target completion date.', null=True)),
                ('estimate_hours', models.DecimalField(decimal_places=2, default=0, help_text='Estimated hours (e.g. 1.5, 2.0).', max_digits=5)),
                ('actual_hours', models.DecimalField(decimal_places=2, default=0, help_text='Total utilized hours across all activities.', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_issues', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Person actually working on this issue.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_issues', to=settings.AUTH_USER_MODEL)),
                ('environment', models.ForeignKey(blank=True, help_text='Optional: specific environment for this issue.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues', to='core.environment')),
                ('project_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_issues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-activity_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InfraActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_date', models.DateField(help_text='Date when this activity was done.')),
                ('status', models.CharField(blank=True, help_text='Optional: status after this activity (e.g. checked, verified).', max_length=20)),
                ('note', models.TextField(blank=True, help_text='Short description of what you did.')),
                ('hours_spent', models.DecimalField(decimal_places=2, default=0, help_text='Hours spent for this activity.', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='core.issue')),
            ],
            options={
                'ordering': ['-activity_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.SlugField(help_text='Short code, e.g. gutta, norisma')),
                ('contact_person', models.CharField(blank=True, max_length=200)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='core.partner')),
            ],
            options={
                'ordering': ['partner', 'name'],
                'unique_together': {('partner', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.SlugField(help_text='Short code, e.g. infra-portal, shop-live')),
                ('description', models.TextField(blank=True)),
                ('repo_url', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='core.client')),
            ],
            options={
                'ordering': ['client', 'name'],
                'unique_together': {('client', 'code')},
            },
        ),
        migrations.AddField(
            model_name='issue',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='core.project'),
        ),
        migrations.AddField(
            model_name='environment',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='environments', to='core.project'),
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('resource_type', models.CharField(choices=[('db', 'Database'), ('bucket', 'Object Storage / Bucket'), ('queue', 'Queue / Messaging'), ('cache', 'Cache / Redis'), ('dns', 'DNS / Domain'), ('other', 'Other')], default='other', max_length=20)),
                ('provider', models.CharField(blank=True, help_text='e.g. RDS, Cloud SQL, S3, Cloudflare', max_length=100)),
                ('identifier', models.CharField(blank=True, help_text='DB name, bucket name, queue name, etc.', max_length=255)),
                ('connection_info', models.TextField(blank=True, help_text='Notes: host:port, endpoint URL, etc.')),
                ('is_critical', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='core.environment')),
            ],
            options={
                'ordering': ['environment', 'resource_type', 'name'],
            },
        ),
        migrations.AddField(
            model_name='issue',
            name='resource',
            field=models.ForeignKey(blank=True, help_text='Optional: specific resource (DB, bucket, DNS, etc.).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues', to='core.resource'),
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. app-1, db-1, nginx-proxy', max_length=200)),
                ('ip_address', models.GenericIPAddressField()),
                ('provider', models.CharField(choices=[('aws', 'AWS'), ('azure', 'Azure'), ('gcp', 'GCP'), ('vps', 'VPS / Other'), ('onprem', 'On-Premise'), ('other', 'Other')], default='other', max_length=20)),
                ('region', models.CharField(blank=True, help_text='e.g. eu-west-1', max_length=100)),
                ('ssh_user', models.CharField(blank=True, max_length=100)),
                ('ssh_port', models.IntegerField(default=22)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servers', to='core.environment')),
            ],
            options={
                'ordering': ['environment', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, help_text='e.g. Consultant, DevOps, Viewer', max_length=100)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.client')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.partner')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='environment',
            unique_together={('project', 'name')},
        ),
    ]
